replace OldWoj="łódzkie" if city=="Aleksandrów Łódzki"
replace OldWoj="bielskie" if city=="Andrychów"
replace OldWoj="tarnobrzeskie" if city=="Annopol"
replace OldWoj="suwalskie" if city=="Augustów"
replace OldWoj="gorzowskie" if city=="Baczyna k. Gorzowa"
replace OldWoj="tarnobrzeskie" if city=="Baranów Sandomierski"
replace OldWoj="gorzowskie" if city=="Barlinek"
replace OldWoj="olsztyńskie" if city=="Bartoszyce"
replace OldWoj="przemyskie" if city=="Basznia Dolna"
replace OldWoj="katowickie" if city=="Będzin"
replace OldWoj="katowickie" if city=="Będzin-Łagisza"
replace OldWoj="piotrkowskie" if city=="Bełchatów"
replace OldWoj="piotrkowskie" if city=="Bełchatów-Rogowiec"
replace OldWoj="zamojskie" if city=="Bełżec"
replace OldWoj="lubelskie" if city=="Bełżyce"
replace OldWoj="bialskopodlaskie" if city==	"Biała Podlaska"
replace OldWoj="bielskie" if city=="Białka k. Makowa Podhalańskiego"
replace OldWoj="radomskie" if city=="Białobrzegi"
replace OldWoj="koszalińskie" if city=="Białogard"
replace OldWoj="warszawskie" if city=="Białołęka"
replace OldWoj="białostockie" if city=="Białystok"
replace OldWoj="nowosądeckie" if city=="Biegonice-Nowy Sącz"
replace OldWoj="bydgoskie" if city=="Bielawy"
replace OldWoj="szczecińskie" if city=="Bielinek"
replace OldWoj="białostockie" if city=="Bielsk Podlaski"
replace OldWoj="bielske" if city=="Bielsko-Biała"
replace OldWoj="zamojskie" if city=="Biłgoraj"
replace OldWoj="opolskie" if city=="Blachownia Śląska"
replace OldWoj="kieleckie" if city=="Bliżyn"
replace OldWoj="piotrkowskie" if city=="Blok Dobroszycki"
replace OldWoj="warszawskie" if city=="Błonie"
replace OldWoj="tarnowskie" if city=="Bochnia"
replace OldWoj="zamojskie" if city=="Bodaczów"
replace OldWoj="jeleniogórskie" if city=="Bogatynia"
replace OldWoj="jeleniogórskie" if city=="Bogatynia-Turoszów"
replace OldWoj="rzeszowskie" if city=="Boguchwała"
replace OldWoj="poznańskie" if city=="Bogucin"
replace OldWoj="jeleniogórskie" if city=="Bolesławiec"
replace OldWoj="elbląskie" if city=="Braniewo"
replace OldWoj="opolskie" if city=="Brzeg"
replace OldWoj="wrocławskie" if city=="Brzeg Dolny"
replace OldWoj="tarnowskie" if city=="Brzesko"
replace OldWoj="włocławskie" if city=="Brzezie k. Włocławka"
replace OldWoj="łódzkie" if city=="Brzeziny k. Łodzi"
replace OldWoj="kaliskie" if city=="Brzostów"
replace OldWoj="krośnieńskie" if city=="Brzozów"
replace OldWoj="poznańskie" if city=="Buk"
replace OldWoj="kieleckie" if city=="Bukowa"
replace OldWoj="kieleckie" if city=="Bukowa Góra"
replace OldWoj="katowickie" if city=="Bukowno"
replace OldWoj="bydgoskie" if city=="Bydgoszcz"
replace OldWoj="bydgoskie" if city=="Bydgoszcz-Fordon"
replace OldWoj="wałbrzyskie" if city=="Bystrzyca"
replace OldWoj="katowickie" if city=="Bytom"
replace OldWoj="słupskie" if city=="Bytów"
replace OldWoj="chełmskie" if city=="Chełm Lubelski"
replace OldWoj="toruńskie" if city=="Chełmno"
replace OldWoj="toruńskie" if city=="Chełmża"
replace OldWoj="legnickie" if city=="Chocianów"
replace OldWoj="pilskie" if city=="Chodzież"
replace OldWoj="bydgoskie" if city=="Chojnice"
replace OldWoj="legnickie" if city=="Chojnów"
replace OldWoj="opolskie" if city=="Chorula gm. Gogolin"
replace OldWoj="katowickie" if city=="Chorzów"
replace OldWoj="katowickie" if city=="Chrzanów"
replace OldWoj="wrocławskie" if city=="Chwalimierz"
replace OldWoj="lubelskie" if city=="Ciecierzyn"
replace OldWoj="wałbrzyskie" if city=="Cierpice"
replace OldWoj="bielskie" if city=="Cieszyn"
replace OldWoj="zielonogórskie" if city=="Cigacice"
replace OldWoj="koszalińskie" if city=="Czaplinek"
replace OldWoj="białostockie" if city=="Czarna Białostocka"
replace OldWoj="radomskie" if city=="Czarna Wieś"
replace OldWoj="gdańskie" if city=="Czarna Woda"
replace OldWoj="słupskie" if city=="Czarne pow. Człuchów"
replace OldWoj="pilskie" if city=="Czarnków"
replace OldWoj="katowickie" if city=="Czechowice"
replace OldWoj="katowickie" if city=="Czechowice-Dziedzice"
replace OldWoj="słupskie" if city=="Człuchów"
replace OldWoj="nowosądeckie" if city=="Czorsztyn"
replace OldWoj="białostockie" if city=="Dąbrowa Białostocka"
replace OldWoj="katowickie" if city=="Dąbrowa Górnicza"
replace OldWoj="katowickie" if city=="Dąbrowa Górnicza-Strzemieszyce"
replace OldWoj="siedleckie" if city=="Dębe Wielkie"
replace OldWoj="tarnowskie" if city=="Dębica"
replace OldWoj="siedleckie" if city=="Dobre"
replace OldWoj="olsztyńskie" if city=="Dobre Miasto"
replace OldWoj="gorzowskie" if city=="Drezdenko"
replace OldWoj="tarnobrzeskie" if city=="Dwikozy"
replace OldWoj="zielonogórskie" if city=="Dychów"
replace OldWoj="kieleckie" if city=="Dyminy"
replace OldWoj="ciechanowskie" if city=="Działdowo"
replace OldWoj="sieradzkie" if city=="Działoszyn"
replace OldWoj="wałbrzyskie" if city=="Dzierżoniów"
replace OldWoj="elbląskie" if city=="Elbląg"
replace OldWoj="suwalskie" if city=="Ełk"
replace OldWoj="kieleckie" if city=="Gacki"
replace OldWoj="poznańskie" if city=="Gądki"
replace OldWoj="siedleckie" if city=="Garwolin"
replace OldWoj="gdańskie" if city=="Gdańsk"
replace OldWoj="gdańskie" if city=="Gdańsk-Maczki"
replace OldWoj="gdańskie" if city=="Gdańsk-Oliwa"
replace OldWoj="gdańskie" if city=="Gdynia"
replace OldWoj="gdańskie" if city=="Gdynia-Cisowa"
replace OldWoj="suwalskie" if city=="Giżycko"
replace OldWoj="warszawskie" if city=="Glina k. Otwocka"
replace OldWoj="ciechanowskie" if city=="Glinojeck"
replace OldWoj="katowickie" if city=="Gliwice"
replace OldWoj="legnickie" if city=="Głogów" | city=="Głogów-Żukowice" 
replace OldWoj="łódzkie" if city=="Głowno"
replace OldWoj="opolskie" if city=="Głuchołazy"
replace OldWoj="gdańskie" if city=="Gniew"
replace OldWoj="przemyskie" if city=="Gniewczyna"
replace OldWoj="poznańskie" if city=="Gniezno"
replace OldWoj="szczecińskie" if city=="Goleniów"
replace OldWoj="warszawskie" if city=="Góra Kalwaria"
replace OldWoj="katowickie" if city=="Górka k. Trzebini"
replace OldWoj="nowosądeckie" if city=="Gorlice"
replace OldWoj="olsztyńskie" if city=="Górowo Iławeckie"
replace OldWoj="piotrkowskie" if city=="Gorzkowice"
replace OldWoj="gorzowskie" if city=="Gorzów"
replace OldWoj="leszczyńskie" if city=="Gostyń"
replace OldWoj="płockie" if city=="Gostynin"
replace OldWoj="zielonogórskie" if city=="Gozdnica"
replace OldWoj="ostrołęckie" if city=="Grabowo"
replace OldWoj="łomżyńskie" if city=="Grajewo"
replace OldWoj="ciechanowskie" if city=="Gralewo"
replace OldWoj="krakowskie" if city=="Grębocin"
replace OldWoj="opolskie" if city=="Grodków"
replace OldWoj="warszawskie" if city=="Grodzisk Mazowiecki"
replace OldWoj="poznańskie" if city=="Grodzisk Wielkopolski"
replace OldWoj="częstochowskie" if city=="Grodzisko"
replace OldWoj="legnickie" if city=="Gromadka"
replace OldWoj="toruńskie" if city=="Grudziądz"
replace OldWoj="nowosądeckie" if city=="Grybów"
replace OldWoj="szczecińskie" if city=="Gryfice"
replace OldWoj="tarnobrzeskie" if city=="Grzybów"
replace OldWoj="zielonogórskie" if city=="Gubin"
replace OldWoj="białostockie" if city=="Hajnówka"
replace OldWoj="tarnobrzeskie" if city=="Harasiuki"
replace OldWoj="zamojskie" if city=="Hedwiżyn pow. Biłgoraj"
replace OldWoj="chełmskie" if city=="Horodyszcze"
replace OldWoj="zamojskie" if city=="Hrubieszów"
replace OldWoj="" if city=="Husaków"
replace OldWoj="olsztyńskie" if city=="Iława"
replace OldWoj="zielonogórskie" if city=="Iława Żagańska"
replace OldWoj="bydgoskie" if city=="Inowrocław"
replace OldWoj="wrocławskie" if city=="Iwiny"
replace OldWoj="bydgoskie" if city=="Janikowo"
replace OldWoj="bydgoskie" if city=="Januszkowo"
replace OldWoj="kaliskie" if city=="Jarocin"
replace OldWoj="przemyskie" if city=="Jarosław"
replace OldWoj="wałbrzyskie" if city=="Jaroszów"
replace OldWoj="katowickie" if city=="Jaroszowiec"
replace OldWoj="zielonogórskie" if city=="Jasień k. Lubska"
replace OldWoj="krośnieńskie" if city=="Jasło"
replace OldWoj="katowickie" if city=="Jastrzębie-Pawłowice"
replace OldWoj="katowickie" if city=="Jastrzębie-Szeroka"
replace OldWoj="katowickie" if city=="Jastrzębie-Zdrój"
replace OldWoj="legnickie" if city=="Jawor"
replace OldWoj="krakowskie" if city=="Jaworzno"
replace OldWoj="wałbrzyskie" if city=="Jaworzyna Śląska"
replace OldWoj="siedleckie" if city=="Jedlanka pow. Łuków"
replace OldWoj="opolskie" if city=="Jedlice k. Ozimka"
replace OldWoj="kieleckie" if city=="Jędrzejów"
replace OldWoj="jeleniogórskie" if city=="Jelenia Góra-Cieplice"
replace OldWoj="bielskie" if city=="Jeleśnia"
replace OldWoj="szczecińskie" if city=="Jezierzyce"
replace OldWoj="tarnobrzeskie" if city=="Jeziorko"
replace OldWoj="nowosądeckie" if city=="Jordanów"
replace OldWoj="zamojskie" if city=="Józefów"
replace OldWoj="częstochowskie" if city=="k. Częstochowy"
replace OldWoj="katowickie" if city=="Kaczyce"
replace OldWoj="chełmskie" if city=="Kanie"
replace OldWoj="warszawskie" if city=="Karczew"
replace OldWoj="koszalińskie" if city=="Karlino"
replace OldWoj="gdańskie" if city=="Kartuzy"
replace OldWoj="katowickie" if city=="Katowice"
replace OldWoj="katowickie" if city=="Katowice Szopienice"
replace OldWoj="katowickie" if city=="Katowice-Dąbrówka"
replace OldWoj="katowickie" if city=="Katowice-Panewnik"
replace OldWoj="opolskie" if city=="Kędzierzyn-Koźle"
replace OldWoj="słupskie" if city=="Kępice"
replace OldWoj="kaliskie" if city=="Kępno"
replace OldWoj="kaliskie" if city=="Kępno-Mianowice"
replace OldWoj="olsztyńskie" if city=="Kętrzyn"
replace OldWoj="bielskie" if city=="Kęty"
replace OldWoj="opolskie" if city=="Kietrz"
replace OldWoj="poznańskie" if city=="Klęka"
replace OldWoj="częstochowskie" if city=="Kłobuck"
replace OldWoj="konińskie" if city=="Kłodawa"
replace OldWoj="wrocławskie" if city=="Kłodzko"
replace OldWoj="opolskie" if city=="Kluczbork"
replace OldWoj="katowickie" if city=="Klucze pow. Olkusz"
replace OldWoj="katowickie" if city=="Knurów"
replace OldWoj="warszawskie" if city=="Kobyłka"
replace OldWoj="częstochowskie" if city=="Kochanowice"
replace OldWoj="gdańskie" if city=="Kokoszki"
replace OldWoj="rzeszowskie" if city=="Kolbuszowa"
replace OldWoj="łomżyńskie" if city=="Kolno"
replace OldWoj="konińskie" if city=="Koło"
replace OldWoj="koszalińskie" if city=="Kołobrzeg"
replace OldWoj="piotrkowskie" if city=="Koluszki"
replace OldWoj="piotrkowskie" if city=="Konewka"
replace OldWoj="częstochowskie" if city=="Koniecpol"
replace OldWoj="częstochowskie" if city=="Koniecpol Chrzęstów"
replace OldWoj="konińskie" if city=="Konin-Jóźwin"
replace OldWoj="konińskie" if city=="Konin-Kazimierz Biskupi"
replace OldWoj="konińskie" if city=="Konin-Kleczew"
replace OldWoj="konińskie" if city=="Konin-Maliniec"
replace OldWoj="kieleckie" if city=="Końskie"
replace OldWoj="warszawskie" if city=="Konstancin-Jeziorna"
replace OldWoj="łódzkie" if city=="Konstantynów Łódzki"
replace OldWoj="bydgoskie" if city=="Koronowo"
replace OldWoj="bydgoskie" if city=="Koronowo-Samociążek"
replace OldWoj="olsztyńskie" if city=="Korsze"
replace OldWoj="konińskie" if city=="Korytków k. Turka"
replace OldWoj="leszczyńskie" if city=="Kościan"
replace OldWoj="gorzowskie" if city=="Kostrzyn n. Odrą"
replace OldWoj="jeleniogórskie" if city=="Kowary"
replace OldWoj="radomskie" if city=="Kozienice"
replace OldWoj="radomskie" if city=="Kozienice-Biała"
replace OldWoj="opolskie" if city=="Koźle-Port"
replace OldWoj="kieleckie" if city=="Kozłów"
replace OldWoj="lubelskie" if city=="Kożuchów"
replace OldWoj="krakowskie" if city=="Kraków"
replace OldWoj="krakowskie" if city=="Kraków-Bieżanów"
replace OldWoj="krakowskie" if city=="Kraków-Czyżyny"
replace OldWoj="krakowskie" if city=="Kraków-Kobierzyn"
replace OldWoj="krakowskie" if city=="Kraków-Nowa Huta"
replace OldWoj="lubelskie" if city=="Kraśnik"
replace OldWoj="chełmskie" if city=="Krasnystaw"
replace OldWoj="kieleckie" if city=="Krasocin"
replace OldWoj="gorzowskie" if city=="Krosno Odrzańskie"
replace OldWoj="kaliskie" if city=="Krotoszyn"
replace OldWoj="bydgoskie" if city=="Kruszwica"
replace OldWoj="krakowskie" if city=="Krzeszowice"
replace OldWoj="zielonogórskie" if city=="Krzywaniec pow. Lubsko"
replace OldWoj="siedleckie" if city=="Kurów"
replace OldWoj="toruńskie" if city=="Kurzętnik"
replace OldWoj="płockie" if city=="Kutno"
replace OldWoj="katowickie" if city=="Kuźnia Raciborska"
replace OldWoj="częstochowskie" if city=="Kuźnica"
replace OldWoj="elbląskie" if city=="Kwidzyn"
replace OldWoj="warszawskie" if city=="Lajski"
replace OldWoj="olsztyńskie" if city=="Łajsy"
replace OldWoj="jeleniogórskie" if city=="Łąka k. Bolesławca"
replace OldWoj="rzeszowskie" if city=="Łańcut"
replace OldWoj="białostockie" if city=="Łapy"
replace OldWoj="sieradzkie" if city=="Łask"
replace OldWoj="siedleckie" if city=="Łaskarzew"
replace OldWoj="wrocławskie" if city=="Laskowice Jelcz"
replace OldWoj="zamojskie" if city=="Łaszczów"
replace OldWoj="katowickie" if city=="Łaziska Górne"
replace OldWoj="słupskie" if city=="Łebieniec"
replace OldWoj="słupskie" if city=="Lębork"
replace OldWoj="lubelskie" if city=="Łęczna"
replace OldWoj="lubelskie" if city=="Łęczna k. Lublina"
replace OldWoj="płockie" if city=="Łęczyca"
replace OldWoj="warszawskie" if city=="Legionowo"
replace OldWoj="legnickie" if city=="Legnica Złotoryjska"
replace OldWoj="radomskie" if city=="Lesiów"
replace OldWoj="łódzkie" if city=="Leśmierz"
replace OldWoj="katowickie" if city=="Leszczyny"
replace OldWoj="zielonogórskie" if city=="Leszno Górne"
replace OldWoj="opolskie" if city=="Lewin Brzeski"
replace OldWoj="rzeszowskie" if city=="Leżajsk"
replace OldWoj="ciechanowskie" if city=="Lidzbark"
replace OldWoj="ciechanowskie" if city=="Lidzbark Warmiński"
replace OldWoj="nowosądeckie" if city=="Limanowa"
replace OldWoj="szczecińskie" if city=="Lipiany"
replace OldWoj="wrocławskie" if city=="Lipno"
replace OldWoj="suwalskie" if city=="Lipsk Suwalski"
replace OldWoj="radomskie" if city=="Lipsko"
replace OldWoj="częstochowskie" if city=="Lisów"
replace OldWoj="częstochowskie" if city=="Lisów pow. Lubliniec"
replace OldWoj="szczecińskie" if city=="Łobez"
replace OldWoj="łódzkie" if city=="Łódź-Widzew"
replace OldWoj="warszawskie" if city=="Łomianki k. Warszawy"
replace OldWoj="łomżyńskie" if city=="Łomża-Kraska"
replace OldWoj="bialskopodlaskie" if city=="Łosice"
replace OldWoj="nowosądeckie" if city=="Łososina Górna"
replace OldWoj="sieradzkie" if city=="Łowicz"
replace OldWoj="przemyskie" if city=="Lubaczów"
replace OldWoj="lubelskie" if city=="Lubartów"
replace OldWoj="olsztyńskie" if city=="Lubawa"
replace OldWoj="jeleniogórskie" if city=="Lubawka pow. Kamienna Góra"
replace OldWoj="gdańskie" if city=="Łubiana"
replace OldWoj="legnickie" if city=="Lubin"
replace OldWoj="częstochowskie" if city=="Lubliniec"
replace OldWoj="zielonogórskie" if city=="Lubsko"
replace OldWoj="siedleckie" if city=="Łuków"
replace OldWoj="tarnobrzeskie" if city=="Machów"
replace OldWoj="elbląskie" if city=="Malbork"
replace OldWoj="ostrołęckie" if city=="Małkinia"
replace OldWoj="kieleckie" if city=="Małogoszcz"
replace OldWoj="zielonogórskie" if city=="Małowice"
replace OldWoj="warszawskie" if city=="Marki k. Warszawy"
replace OldWoj="bielskie" if city=="Marklowice k. Cieszyna"
replace OldWoj="toruńskie" if city=="Marusza k. Grudziądza"
replace OldWoj="katowickie" if city=="Miechowice-Bytom"
replace OldWoj="bielskie" if city=="Międzybrodzie-Żywieckie"
replace OldWoj="gorzowskie" if city=="Międzychód"
replace OldWoj="bialskopodlaskie" if city=="Międzyrzec Podlaski"
replace OldWoj="rzeszowskie" if city=="Mielec"
replace OldWoj="białostockie" if city=="Mielnik"
replace OldWoj="katowickie" if city=="Mikołów"
replace OldWoj="warszawskie" if city=="Milanówek"
replace OldWoj="lubelskie" if city=="Milejów"
replace OldWoj="siedleckie" if city=="Mińsk Mazowiecki"
replace OldWoj="pilskie" if city=="Mirosław Ujski"
replace OldWoj="ciechanowskie" if city=="Mława"
replace OldWoj="kieleckie" if city=="Mniszek pow. Jędrzejów"
replace OldWoj="bydgoskie" if city=="Mogilno"
replace OldWoj="białostockie" if city=="Mońki"
replace OldWoj="olsztyńskie" if city=="Morąg"
replace OldWoj="kieleckie" if city=="Morawica"
replace OldWoj="olsztyńskie" if city=="Mrągowo"
replace OldWoj="koszalińskie" if city=="Mścice"
replace OldWoj="skierniewickie" if city=="Mszczonów"
replace OldWoj="przemyskie" if city=="Munina"
replace OldWoj="opolskie" if city=="Murów"
replace OldWoj="krośnieńskie" if city=="Myczkowce"
replace OldWoj="krakowskie" if city=="Myślenice"
replace OldWoj="katowickie" if city=="Mysłowice"
replace OldWoj="częstochowskie" if city=="Myszków"
replace OldWoj="bydgoskie" if city=="Nakło n. Notecią"
replace OldWoj="ciechanowskie" if city=="Nasielsk"
replace OldWoj="olsztyńskie" if city=="Nidzica"
replace OldWoj="ciechanowskie" if city=="Niegocin"
replace OldWoj="krakowskie" if city=="Niepołomice"
replace OldWoj="kieleckie" if city=="Niewachlów"
replace OldWoj="tarnobrzeskie" if city=="Nisko"
replace OldWoj="jeleniogórskie" if city=="Niwnice"
replace OldWoj="wałbrzyskie" if city=="Nowa Ruda"
replace OldWoj="rzeszowskie" if city=="Nowa Sarzyna"
replace OldWoj="zielonogórskie" if city=="Nowa Sól"
replace OldWoj="katowickie" if city=="Nowa Wieś"
replace OldWoj="bydgoskie" if city=="Nowe"
replace OldWoj="szczecińskie" if city=="Nowe Czarnowo"
replace OldWoj="katowickie" if city=="Nowe Tychy"
replace OldWoj="szczecińskie" if city=="Nowogard"
replace OldWoj="zielonogórskie" if city=="Nowogród Bobrzański"
replace OldWoj="warszawskie" if city=="Nowy Dwór Mazowiecki"
replace OldWoj="jeleniogórskie" if city=="Nowy Kościół"
replace OldWoj="nowosądeckie" if city=="Nowy sącz"
replace OldWoj="nowosądeckie" if city=="Nowy Targ"
replace OldWoj="opolskie" if city=="Nysa"
replace OldWoj="poznańskie" if city=="Oborniki Wielkopolskie"
replace OldWoj="kaliskie" if city=="Odolanów"
replace OldWoj="jeleniogórskie" if city=="Ogorzelec"
replace OldWoj="katowickie" if city=="Ogrodzieniec"
replace OldWoj="jeleniogórskie" if city=="Ołdrzyków pow. bolesławski"
replace OldWoj="suwalskie" if city=="Olecko"
replace OldWoj="wrocławskie" if city=="Oleśnica"
replace OldWoj="katowickie" if city=="Olkusz"
replace OldWoj="toruńskie" if city=="Olszówka pow. Golub"
replace OldWoj="olsztyńskie" if city=="Olsztynek"
replace OldWoj="piotrkowskie" if city=="Opoczno"
replace OldWoj="katowickie" if city=="Ornontowice"
replace OldWoj="legnickie" if city=="Orsk-Rudna"
replace OldWoj="katowickie" if city=="Orzesze"
replace OldWoj="gdańskie" if city=="Osiek"
replace OldWoj="częstochowskie" if city=="Osiny"
replace OldWoj="słupskie" if city=="Osława-Dąbrowa"
replace OldWoj="olsztyńskie" if city=="Ostróda"
replace OldWoj="ostrołęckie" if city=="Ostrów Mazowiecka"
replace OldWoj="kaliskie" if city=="Ostrów Wielkopolski"
replace OldWoj="siedleckie" if city=="Ostrówek Węgrowski"
replace OldWoj="kieleckie" if city=="Ostrowiec Świętokrzyski"
replace OldWoj="kaliskie" if city=="Ostrzeszów"
replace OldWoj="bielskie" if city=="Oświęcim"
replace OldWoj="opolskie" if city=="Otmęt"
replace OldWoj="tarnobrzeskie" if city=="Ożarów" 
replace OldWoj="warszawskie" if city=="Ożarów Mazowiecki"
replace OldWoj="opolskie" if city=="Ozimek"
replace OldWoj="łódzkie" if city=="Ozorków"
replace OldWoj="łódzkie" if city=="Pabianice"
replace OldWoj="bydgoskie" if city=="Pakość"
replace OldWoj="elbląskie" if city=="Pasłęk"
replace OldWoj="bydgoskie" if city=="Paterek k. Nakła"
replace OldWoj="sieradzkie" if city=="Pątnów"
replace OldWoj="bydgoskie" if city=="Peplin"
replace OldWoj="warszawskie" if city=="Piaseczno"
replace OldWoj="tarnobrzeskie" if city=="Piaseczno k. Tarnobrzega"
replace OldWoj="bydgoskie" if city=="Piechocin-Bielawy"
replace OldWoj="jeleniogórskie" if city=="Piechowice Dolne"
replace OldWoj="katowickie" if city=="Piekary Śląskie"
replace OldWoj="elbląskie" if city=="Pieniężno"
replace OldWoj="słupskie" if city=="Pieńkowo pow. Sławno"
replace OldWoj="siedleckie" if city=="Pilawa"
replace OldWoj="siedleckie" if city=="Piława"
replace OldWoj="kieleckie" if city=="Pińczów"
replace OldWoj="radomskie" if city=="Pionki"
replace OldWoj="katowickie" if city=="Piotrowice-Katowice"
replace OldWoj="suwalskie" if city=="Pisz"
replace OldWoj="kaliskie" if city=="Pleszew"
replace OldWoj="płockie" if city=="Płock-Biała Nowa"
replace OldWoj="ciechanowskie" if city=="Płońsk"
replace OldWoj="poznańskie" if city=="Pniewy"
replace OldWoj="olsztyńskie" if city=="Podleśna"
replace OldWoj="rzeszowskie" if city=="Pogwizdów Nowy k. Rzeszowa"
replace OldWoj="tarnobrzeskie" if city=="Połaniec"
replace OldWoj="szczecińskie" if city=="Police-Jasienice Szczecińskie"
replace OldWoj="legnickie" if city=="Polkowice"
replace OldWoj="legnickie" if city=="Polkowice-Rudna"
replace OldWoj="katowickie" if city=="Pomorzany"
replace OldWoj="katowickie" if city=="Pomorzany k. Olkusza"
replace OldWoj="lubelskie" if city=="Poniatowa"
replace OldWoj="zielonogórskie" if city=="Powodowo pow. Wolsztyn"
replace OldWoj="poznańskie" if city=="Poznań"
replace OldWoj="poznańskie" if city=="Poznań - Kobyle Pole"
replace OldWoj="poznańskie" if city=="Poznań-Antonin"
replace OldWoj="poznańskie" if city=="Poznań-Barwice"
replace OldWoj="poznańskie" if city=="Poznań-Karolin"
replace OldWoj="poznańskie" if city=="Poznań-Koziegłowy"
replace OldWoj="poznańskie" if city=="Poznań-Suchy Las"
replace OldWoj="sieradzkie" if city=="Praszka"
replace OldWoj="gdańskie" if city=="Pruszcz Gdański"
replace OldWoj="warszawskie" if city=="Pruszków"
replace OldWoj="ostrołęckie" if city=="Przasnysz"
replace OldWoj="przemyskie" if city=="Przeworsk"
replace OldWoj="bydgoskie" if city=="Przyłęki"
replace OldWoj="zielonogórskie" if city=="Przylep"
replace OldWoj="katowickie" if city=="Pszczyna"
replace OldWoj="lubelskie" if city=="Puławy"
replace OldWoj="ciechanowskie" if city=="Pułtusk"
replace OldWoj="katowickie" if city=="Racibórz"
replace OldWoj="radomskie" if city=="Radom-Potkanów"
replace OldWoj="piotrkowskie" if city=="Radomsko"
replace OldWoj="wrocławskie" if city=="Radwanice-Jakubów"
replace OldWoj="przemyskie" if city=="Radymno"
replace OldWoj="warszawskie" if city=="Radzymin"
replace OldWoj="bialskopodlaskie" if city=="Radzyń Podlaski"
replace OldWoj="łomżyńskie" if city=="Rajgród"
replace OldWoj="bielskie" if city=="Rajsk k. Oświęcimia"
replace OldWoj="jeleniogórskie" if city=="Rakowice Małe"
replace OldWoj="skierniewickie" if city=="Rawa Mazowiecka"
replace OldWoj="leszczyńskie" if city=="Rawicz"
replace OldWoj="skierniewickie" if city=="Rawka k. Skierniewic"
replace OldWoj="chełmskie" if city=="Rejowiec Fabryczny"
replace OldWoj="piotrkowskie" if city=="Rogowiec k. Bełchatowa"
replace OldWoj="pilskie" if city=="Rogoźno"
replace OldWoj="rzeszowskie" if city=="Ropczyce"
replace OldWoj="nowosądeckie" if city=="Rożnów-Czchów"
replace OldWoj="suwalskie" if city=="Ruciane"
replace OldWoj="suwalskie" if city=="Ruciane-Nida"
replace OldWoj="katowickie" if city=="Ruda Śląska"
replace OldWoj="toruńskie" if city=="Rudki"
replace OldWoj="rzeszowskie" if city=="Rudna"
replace OldWoj="częstochowskie" if city=="Rudniki"
replace OldWoj="katowickie" if city=="Rybnik"
replace OldWoj="katowickie" if city=="Rybnik-Kłokocin"
replace OldWoj="lubelskie" if city=="Ryki"
replace OldWoj="krośnieńskie" if city=="Rymanów"
replace OldWoj="wrocławskie" if city=="Rypin"
replace OldWoj="słupskie" if city=="Rzeczenica"
replace OldWoj="krośnieńskie" if city=="Rzepedź pow. Sanok"
replace OldWoj="rzeszowskie" if city=="Rzeszów Tyczyn"
replace OldWoj="częstochowskie" if city=="Sabinów"
replace OldWoj="tarnobrzeskie" if city=="Sandomierz"
replace OldWoj="krośnieńskie" if city=="Sanok"
replace OldWoj="legnickie" if city=="Ścinawa"
replace OldWoj="kieleckie" if city=="Sędziszów"
replace OldWoj="rzeszowskie" if city=="Sędziszów Małopolski"
replace OldWoj="tarnowskie" if city=="Siedlec-Moszczenica"
replace OldWoj="katowickie" if city=="Siemianowice"
replace OldWoj="katowickie" if city=="Siemianowice Śląskie"
replace OldWoj="białostockie" if city=="Siemiatycze"
replace OldWoj="gdańskie" if city=="Sierakowice"
replace OldWoj="płockie" if city=="Sierpc"
replace OldWoj="katowickie" if city=="Siewierz"
replace OldWoj="kieleckie" if city=="Sitkówka"
replace OldWoj="kieleckie" if city=="Sitkówka k. Kielc"
replace OldWoj="kieleckie" if city=="Sitkówka-Nowiny"
replace OldWoj="kieleckie" if city=="Skarżysko-Kamienna"
replace OldWoj="krakowskie" if city=="Skawina"
replace OldWoj="płockie" if city=="Sklęczki k. Kutna"
replace OldWoj="bielskie" if city=="Skoczów"
replace OldWoj="wrocławskie" if city=="Skokowa"
replace OldWoj="tarnobrzeskie" if city=="Skopanie"
replace OldWoj="opolskie" if city=="Sławniowice"
replace OldWoj="słupskie" if city=="Sławno"
replace OldWoj="gorzowskie" if city=="Słubice"
replace OldWoj="konińskie" if city=="Słupca"
replace OldWoj="łomżyńskie" if city=="Śniadowo pow. Łomża"
replace OldWoj="białostockie" if city=="Sobolewo"
replace OldWoj="białostockie" if city=="Sokółka"
replace OldWoj="siedleckie" if city=="Sokołów Podlaski"
replace OldWoj="bydgoskie" if city=="Solec Kujawski"
replace OldWoj="krośnieńskie" if city=="Solina-Myczkowce"
replace OldWoj="gdańskie" if city=="Sopot"
replace OldWoj="katowickie" if city=="Sosnowiec"
replace OldWoj="katowickie" if city=="Sosnowiec-Porąbka"
replace OldWoj="piotrkowskie" if city=="Spała"
replace OldWoj="olsztyńskie" if city=="Spychów"
replace OldWoj="poznańskie" if city=="Śrem"
replace OldWoj="poznańskie" if city=="Środa Wielkopolska"
replace OldWoj="tarnobrzeskie" if city=="Stalowa Wola"
replace OldWoj="kieleckie" if city=="Stąporków"
replace OldWoj="kieleckie" if city=="Starachowice"
replace OldWoj="szczecińskie" if city=="Stargard Szczeciński"
replace OldWoj="gdańskie" if city=="Starogard Gdański"
replace OldWoj="chełmskie" if city=="Stefanów"
replace OldWoj="gdańskie" if city=="Straszyn-Gdańsk"
replace OldWoj="wałbrzyskie" if city=="Strzegom"
replace OldWoj="wałbrzyskie" if city=="Strzegoń-Sobótka"
replace OldWoj="opolskie" if city=="Strzelce Opolskie"
replace OldWoj="rzeszowskie" if city=="Strzyżów"
replace OldWoj="rzeszowskie" if city=="Strzyżów n. Wisłokiem"
replace OldWoj="kieleckie" if city=="Suchedniów"
replace OldWoj="zielonogórskie" if city=="Sulechów"
replace OldWoj="piotrkowskie" if city=="Sulejów"
replace OldWoj="katowickie" if city=="Suszec"
replace OldWoj="suwalskie" if city=="Suwałki-Papiernia"
replace OldWoj="wałbrzyskie" if city=="Świdnica"
replace OldWoj="lubelskie" if city=="Świdnik"
replace OldWoj="wałbrzyskie" if city=="Świebodzice"
replace OldWoj="zielonogórskie" if city=="Świebodzin"
replace OldWoj="bydgoskie" if city=="Świecie n. Wisłą"
replace OldWoj="warszawskie" if city=="Świerk"
replace OldWoj="katowickie" if city=="Świerklaniec-Piekary Śląskie"
replace OldWoj="radomskie" if city=="Świerże Górne"
replace OldWoj="szczecińskie" if city=="Świnoujście"
replace OldWoj="nowosądeckie" if city=="Szaflary k. Nowego Targu"
replace OldWoj="poznańskie" if city=="Szamotuły"
replace OldWoj="nowosądeckie" if city=="Szczawnica"
replace OldWoj="szczecińskie" if city=="Szczecin-Dąbie"
replace OldWoj="koszalińskie" if city=="Szczecinek"
replace OldWoj="szczecińskie" if city=="Szczecin-Płonie"
replace OldWoj="tarnowskie" if city=="Szczucin"
replace OldWoj="olsztyńskie" if city=="Szczytno"
replace OldWoj="jeleniogórskie" if city=="Szklarska Poręba"
replace OldWoj="radomskie" if city=="Szydłowiec"
replace OldWoj="warszawskie" if city=="Tarczyn k. Warszawy"
replace OldWoj="opolskie" if city=="Tarnów Opolski"
replace OldWoj="katowickie" if city=="Tarnowskie Góry"
replace OldWoj="gdańskie" if city=="Tczew"
replace OldWoj="sieradzkie" if city=="Teodory pow. Łask"
replace OldWoj="skierniewickie" if city=="Teresin"
replace OldWoj="ostrołęckie" if city=="Tłuszcz"
replace OldWoj="piotrkowskie" if city=="Tomaszów Mazowiecki"
replace OldWoj="katowickie" if city=="Toszek"
replace OldWoj="lubelskie" if city=="Trawniki"
replace OldWoj="bielskie" if city=="Tresna"
replace OldWoj="pilskie" if city=="Trzcianka"
replace OldWoj="szczecińskie" if city=="Trzebiatów"
replace OldWoj="katowickie" if city=="Trzebinia" | city=="Trzebina"
replace OldWoj="bydgoskie" if city=="Trzemeszno"
replace OldWoj="bydgoskie" if city=="Tuchola"
replace OldWoj="opolskie" if city=="Tułowice"
replace OldWoj="konińskie" if city=="Turek"
replace OldWoj="katowickie" if city=="Tychy"
replace OldWoj="katowickie" if city=="Tychy Lędziny"
replace OldWoj="katowickie" if city=="Tychy-Bieruń Nowy"
replace OldWoj="legnickie" if city=="Ujazd Dolny"
replace OldWoj="elbląskie" if city=="Uśnice"
replace OldWoj="krośnieńskie" if city=="Ustianowa"
replace OldWoj="bielskie" if city=="Ustroń k. Cieszyna"
replace OldWoj="krośnieńskie" if city=="Ustrzyki Dolne"
replace OldWoj="częstochowskie" if city=="Wachów"
replace OldWoj="bielskie" if city=="Wadowice"
replace OldWoj="radomskie" if city=="Wał"
replace OldWoj="pilskie" if city=="Wałcz"
replace OldWoj="pilskie" if city=="Wałcz-Jastrowie"
replace OldWoj="bielskie" if city=="Wapiennica"
replace OldWoj="olsztyńskie" if city=="Waplewo"
replace OldWoj="konińskie" if city=="Warenka k. Turka"
replace OldWoj="konińskie" if city=="Warenka-Turek"
replace OldWoj="radomskie" if city=="Warka"
replace OldWoj="warszawskie" if city=="Warszawa"
replace OldWoj="warszawskie" if city=="Warszawa Międzylesie"
replace OldWoj="warszawskie" if city=="Warszawa Targówek"
replace OldWoj="warszawskie" if city=="Warszawa-Falenica"
replace OldWoj="warszawskie" if city=="Warszawa-Mokotów"
replace OldWoj="warszawskie" if city=="Warszawa-Siekierki"
replace OldWoj="warszawskie" if city=="Warszawa-Służew"
replace OldWoj="warszawskie" if city=="Warszawa-Służewiec"
replace OldWoj="warszawskie" if city=="Warszawa-Tarchomin"
replace OldWoj="warszawskie" if city=="Warszawa-Żerań"
replace OldWoj="suwalskie" if city=="Węgorzewo"
replace OldWoj="siedleckie" if city=="Węgrów"
replace OldWoj="zamojskie" if city=="Werbkowice"
replace OldWoj="sieradzkie" if city=="Wielenin pow. Poddębice"
replace OldWoj="warszawskie" if city=="Wieliszew"
replace OldWoj="sieradzkie" if city=="Wieluń"
replace OldWoj="katowickie" if city=="Wierbka"
replace OldWoj="kaliskie" if city=="Wieruszów"
replace OldWoj="radomskie" if city=="Wierzbica"
replace OldWoj="suwalskie" if city=="Wilkasy k. Giżycka"
replace OldWoj="legnickie" if city=="Wilków"
replace OldWoj="kaliskie" if city=="Witaszyce"
replace OldWoj="gdańskie" if city=="Władysławowo"
replace OldWoj="chełmskie" if city=="Włodawa-Orchówek"
replace OldWoj="kieleckie" if city=="Włoszczowa"
replace OldWoj="katowickie" if city=="Wodzisław Śląski"
replace OldWoj="katowickie" if city=="Wola k. Pszczyny"
replace OldWoj="tarnobrzeskie" if city=="Wola Rzędzińska gm. Tarnów"
replace OldWoj="katowickie" if city=="Wolbrom"
replace OldWoj="warszawskie" if city=="Wołomin"
replace OldWoj="zielonogórskie" if city=="Wolsztyn"
replace OldWoj="częstochowskie" if city=="Wręczyca"
replace OldWoj="wrocławskie" if city=="Wrocław"
replace OldWoj="wrocławskie" if city=="Wrocław-Fabryczna"
replace OldWoj="pilskie" if city=="Wronki"
replace OldWoj="poznańskie" if city=="Września"
replace OldWoj="ostrołęckie" if city=="Wyszków"
replace OldWoj="" if city=="Ząbkowice"
replace OldWoj="wałbrzyskie" if city=="Ząbkowice Śląskie" | city=="Ząbkowice"
replace OldWoj="katowickie" if city=="Zabrze"
replace OldWoj="katowickie" if city=="Zabrze-Mikulczyce"
replace OldWoj="warszawskie" if city=="Zacisze Górne"
replace OldWoj="zielonogórskie" if city=="Żagań"
replace OldWoj="katowickie" if city=="Zagórze k. Będzina"
replace OldWoj="nowosądeckie" if city=="Zakopane"
replace OldWoj="łomżyńskie" if city=="Zambrów"
replace OldWoj="gdańskie" if city=="Żarnowiec"
replace OldWoj="gorzowskie" if city=="Żary"
replace OldWoj="opolskie" if city=="Zawadzkie"
replace OldWoj="jeleniogórskie" if city=="Zawidów"
replace OldWoj="katowickie" if city=="Zawiercie"
replace OldWoj="katowickie" if city=="Zawiercie-Ogrodzieniec"
replace OldWoj="sieradzkie" if city=="Zduńska Wola"
replace OldWoj="opolskie" if city=="Zdzieszowice"
replace OldWoj="radomskie" if city=="Zębiec k. Iłży"
replace OldWoj="siedleckie" if city=="Żelechów"
replace OldWoj="katowickie" if city=="Żelisławice"
replace OldWoj="krakowskie" if city=="Zesławice"
replace OldWoj="łódzkie" if city=="Zgierz"
replace OldWoj="łódzkie" if city=="Zgierz-Rudniki"
replace OldWoj="jeleniogórskie" if city=="Zgorzelec"
replace OldWoj="warszawskie" if city=="Zielonka k. Warszawy"
replace OldWoj="legnickie" if city=="Złotoryja"
replace OldWoj="pilskie" if city=="Złotów"
replace OldWoj="katowickie" if city=="Żory k. Rybnika"
replace OldWoj="katowickie" if city=="Żory-Zdrój"
replace OldWoj="szczecińskie" if city=="Żuków"
replace OldWoj="gdańskie" if city=="Żukowo"
replace OldWoj="warszawskie" if city=="Żuromin"
replace OldWoj="poznańskie" if city=="Żydowo"
replace OldWoj="skierniewickie" if city=="Żyrardów"
replace OldWoj="radomskie" if city=="Żytkowice"
replace OldWoj="bielskie" if city=="Żywiec"

replace OldWoj="bialskopodlaskie" if city=="Biała Podlaska"
replace OldWoj="białostockie" if city=="Białystok"
replace OldWoj="bielskie" if city=="Bielsko-Biała"
replace OldWoj="bydgoskie" if city=="Bydgoszcz"
replace OldWoj="chełmskie" if city=="Chełm"
replace OldWoj="ciechanowskie" if city=="Ciechanów"
replace OldWoj="częstochowskie" if city=="Częstochowa"
replace OldWoj="elbląskie" if city=="Elbląg"
replace OldWoj="gdańskie" if city=="Gdańsk"
replace OldWoj="gorzowskie" if city=="Gorzów Wielkopolski"
replace OldWoj="jeleniogórskie" if city=="Jelenia Góra"
replace OldWoj="kaliskie" if city=="Kalisz"
replace OldWoj="katowickie" if city=="Katowice"
replace OldWoj="kieleckie" if city=="Kielce"
replace OldWoj="konińskie" if city=="Konin"
replace OldWoj="koszalińskie" if city=="Koszalin"
replace OldWoj="krakowskie" if city=="Kraków"
replace OldWoj="krośnieńskie" if city=="Krosno"
replace OldWoj="legnickie" if city=="Legnica"
replace OldWoj="leszczyńskie" if city=="Leszno"
replace OldWoj="lubelskie" if city=="Lublin"
replace OldWoj="łomżyńskie" if city=="Łomża"
replace OldWoj="łódzkie" if city=="Łódź"
replace OldWoj="nowosądeckie" if city=="Nowy Sącz"
replace OldWoj="olsztyńskie" if city=="Olsztyn"
replace OldWoj="opolskie" if city=="Opole"
replace OldWoj="ostrołęckie" if city=="Ostrołęka"
replace OldWoj="pilskie" if city=="Piła"
replace OldWoj="piotrkowskie" if city=="Piotrków Trybunalski"
replace OldWoj="płockie" if city=="Płock"
replace OldWoj="poznańskie" if city=="Poznań"
replace OldWoj="przemyskie" if city=="Przemyśl"
replace OldWoj="radomskie" if city=="Radom"
replace OldWoj="rzeszowskie" if city=="Rzeszów"
replace OldWoj="siedleckie" if city=="Siedlce"
replace OldWoj="sieradzkie" if city=="Sieradz"
replace OldWoj="skierniewickie" if city=="Skierniewice"
replace OldWoj="słupskie" if city=="Słupsk"
replace OldWoj="suwalskie" if city=="Suwałki"
replace OldWoj="szczecińskie" if city=="Szczecin"
replace OldWoj="tarnobrzeskie" if city=="Tarnobrzeg"
replace OldWoj="tarnowskie" if city=="Tarnów"
replace OldWoj="toruńskie" if city=="Toruń"
replace OldWoj="wałbrzyskie" if city=="Wałbrzych"
replace OldWoj="włocławskie" if city=="Włocławek"
replace OldWoj="warszawskie" if city=="Warszawa"
replace OldWoj="zamojskie" if city=="Zamość"
replace OldWoj="zielonogórskie" if city=="Zielona Góra"


//specific cases where town name is missing but name of plant can be deducted from location
replace OldWoj= "konińskie" if entity == "Zespół Elektrowni Pątnów-Adamów"
replace OldWoj= "gdańskie" if entity == "Zespół Elektrociepłowni Gdańsk"
replace OldWoj= "katowickie" if entity == "Kopalnia Rudy Żelaza" & yob ==1953
replace OldWoj= "szczecińskie" if entity == "Zespół Elektrowni Dolna Odra"


do prep00_03_OldWoj_cleaning2
