replace reg49 = 1 if OldWoj == "warszawskie"
replace reg49 = 1 if OldWoj == "warszawskie"
replace reg49 = 3 if OldWoj == "bialskopodlaskie"
replace reg49 = 3 if OldWoj == "bialskopodlaskie"
replace reg49 = 5 if OldWoj == "białostockie"
replace reg49 = 5 if OldWoj == "białostockie"
replace reg49 = 7 if OldWoj == "bielskie"
replace reg49 = 7 if OldWoj == "bielskie"
replace reg49 = 9 if OldWoj == "bydgoskie"
replace reg49 = 9 if OldWoj == "bydgoskie"
replace reg49 = 11 if OldWoj == "chełmskie"
replace reg49 = 11 if OldWoj == "chełmskie"
replace reg49 = 13 if OldWoj == "ciechanowskie"
replace reg49 = 13 if OldWoj == "ciechanowskie"
replace reg49 = 15 if OldWoj == "częstochowskie"
replace reg49 = 15 if OldWoj == "częstochowskie"
replace reg49 = 17 if OldWoj == "elbląskie"
replace reg49 = 17 if OldWoj == "elbląskie"
replace reg49 = 19 if OldWoj == "gdańskie"
replace reg49 = 19 if OldWoj == "gdańskie"
replace reg49 = 21 if OldWoj == "gorzowskie"
replace reg49 = 21 if OldWoj == "gorzowskie"
replace reg49 = 23 if OldWoj == "jeleniogórskie"
replace reg49 = 23 if OldWoj == "jeleniogórskie"
replace reg49 = 25 if OldWoj == "kaliskie"
replace reg49 = 25 if OldWoj == "kaliskie"
replace reg49 = 27 if OldWoj == "katowickie"
replace reg49 = 27 if OldWoj == "katowickie"
replace reg49 = 29 if OldWoj == "kieleckie"
replace reg49 = 29 if OldWoj == "kieleckie"
replace reg49 = 31 if OldWoj == "konińskie"
replace reg49 = 31 if OldWoj == "konińskie"
replace reg49 = 33 if OldWoj == "koszalińskie"
replace reg49 = 33 if OldWoj == "koszalińskie"
replace reg49 = 35 if OldWoj == "krakowskie"
replace reg49 = 35 if OldWoj == "krakowskie"
replace reg49 = 37 if OldWoj == "krośnieńskie"
replace reg49 = 37 if OldWoj == "krośnieńskie"
replace reg49 = 39 if OldWoj == "legnickie"
replace reg49 = 39 if OldWoj == "legnickie"
replace reg49 = 41 if OldWoj == "leszczyńskie"
replace reg49 = 41 if OldWoj == "leszczyńskie"
replace reg49 = 43 if OldWoj == "lubelskie"
replace reg49 = 43 if OldWoj == "lubelskie"
replace reg49 = 45 if OldWoj == "łomżyńskie"
replace reg49 = 45 if OldWoj == "łomżyńskie"
replace reg49 = 47 if OldWoj == "łódzkie"
replace reg49 = 47 if OldWoj == "łódzkie"
replace reg49 = 49 if OldWoj == "nowosądeckie"
replace reg49 = 49 if OldWoj == "nowosądeckie"
replace reg49 = 51 if OldWoj == "olsztyńskie"
replace reg49 = 51 if OldWoj == "olsztyńskie"
replace reg49 = 53 if OldWoj == "opolskie"
replace reg49 = 53 if OldWoj == "opolskie"
replace reg49 = 55 if OldWoj == "ostrołęckie"
replace reg49 = 55 if OldWoj == "ostrołęckie"
replace reg49 = 57 if OldWoj == "pilskie"
replace reg49 = 57 if OldWoj == "pilskie"
replace reg49 = 59 if OldWoj == "piotrkowskie"
replace reg49 = 59 if OldWoj == "piotrkowskie"
replace reg49 = 61 if OldWoj == "płockie"
replace reg49 = 61 if OldWoj == "płockie"
replace reg49 = 63 if OldWoj == "poznańskie"
replace reg49 = 63 if OldWoj == "poznańskie"
replace reg49 = 65 if OldWoj == "przemyskie"
replace reg49 = 65 if OldWoj == "przemyskie"
replace reg49 = 67 if OldWoj == "radomskie"
replace reg49 = 67 if OldWoj == "radomskie"
replace reg49 = 69 if OldWoj == "rzeszowskie"
replace reg49 = 69 if OldWoj == "rzeszowskie"
replace reg49 = 71 if OldWoj == "siedleckie"
replace reg49 = 71 if OldWoj == "siedleckie"
replace reg49 = 73 if OldWoj == "sieradzkie"
replace reg49 = 73 if OldWoj == "sieradzkie"
replace reg49 = 75 if OldWoj == "skierniewickie"
replace reg49 = 75 if OldWoj == "skierniewickie"
replace reg49 = 77 if OldWoj == "słupskie"
replace reg49 = 77 if OldWoj == "słupskie"
replace reg49 = 79 if OldWoj == "suwalskie"
replace reg49 = 79 if OldWoj == "suwalskie"
replace reg49 = 81 if OldWoj == "szczecińskie"
replace reg49 = 81 if OldWoj == "szczecińskie"
replace reg49 = 83 if OldWoj == "tarnobrzeskie"
replace reg49 = 83 if OldWoj == "tarnobrzeskie"
replace reg49 = 85 if OldWoj == "tarnowskie"
replace reg49 = 85 if OldWoj == "tarnowskie"
replace reg49 = 87 if OldWoj == "toruńskie"
replace reg49 = 87 if OldWoj == "toruńskie"
replace reg49 = 89 if OldWoj == "wałbrzyskie"
replace reg49 = 89 if OldWoj == "wałbrzyskie"
replace reg49 = 91 if OldWoj == "włocławskie"
replace reg49 = 91 if OldWoj == "włocławskie"
replace reg49 = 93 if OldWoj == "wrocławskie"
replace reg49 = 93 if OldWoj == "wrocławskie"
replace reg49 = 95 if OldWoj == "zamojskie"
replace reg49 = 95 if OldWoj == "zamojskie"
replace reg49 = 97 if OldWoj == "zielonogórskie"
replace reg49 = 97 if OldWoj == "zielonogórskie" 









// The full list of regions and cities in the document below
// list of all counties in PL, with post-1999 regions
// import delimited "data/SIMC_Urzedowy_1999-11-26.csv", delimiter(";") encoding(utf8)  clear
// ren nazwa city
// save "data/SIMC_Urzedowy_1999-11-26.dta", replace
// duplicates drop woj city
